"""Reward function registry for reinforcement learning."""
from typing import Callable, Dict, List

# Example reward function

def reward_length(tokens: List[int], **kwargs) -> float:
    """Return the number of tokens before an EOS token.

    Args:
        tokens: Sequence of token ids generated by the model.

    Returns:
        float: Length of the sequence excluding the final EOS token if present.
    """
    if len(tokens) == 0:
        return 0.0
    if tokens[-1] == kwargs.get("eos", None):
        return float(len(tokens) - 1)
    return float(len(tokens))

REWARD_FNS: Dict[str, Callable] = {"length": reward_length}

def get_reward_fn(name: str) -> Callable:
    """Fetch a reward function by name."""
    if name not in REWARD_FNS:
        raise KeyError(f"Unknown reward function: {name}")
    return REWARD_FNS[name]
